### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by ralscha** [eakoriakin/ionic-selectable#215] opened 2019-11-20 08:31 UTC
`ionic-selectable.component.ts` references `Renderer` which no longer exists in Angular 9.

https://github.com/eakoriakin/ionic-selectable/blob/master/src/app/components/ionic-selectable/ionic-selectable.component.ts#L2

Replacement is `Renderer2` which exists for quite some time. I think it has been introduced in Angular 4.

**Comment by edy-ap** [comment] 2019-11-20 16:37
The issue is solved in #216. Will be integrated in the next release.
Thanks for you contribution.

**Closed** 2020-01-20 22:17 UTC
Labels: next-version
