### ISSUE TITLE
onInfiniteScroll blink and redisplay all item but old plugin display only new items

### ISSUE THREAD

**Issue by rupendraa** [eakoriakin/ionic-selectable#180] opened 2019-06-17 06:54 UTC
i am updating ionic 3 app to ionic 4 
so your old plugin ionic-select-searchable to ionic-selectable
when use  [hasInfiniteScroll]="true" (onInfiniteScroll)="getMorePorts($event)"
display items show after blink but in old plugin its fill only new items 
in new plugin blink all old item also like clear all item and re-display
can you solve this problem

**Comment by rupendraa** [comment] 2019-06-27 04:47
can you give me old plugin source code=> ionic-select-searchable@1.1.3

**Comment by eakoriakin** [comment] 2019-06-27 04:55
That is a known issue and a duplicate of 164.

**Closed by eakoriakin** 2019-06-27 04:55 UTC
